'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class ITCWelcome

    '''<summary>
    '''hdDiscount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdDiscount As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''PlanSelectionDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlanSelectionDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''welcomeNoteWrapper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents welcomeNoteWrapper As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblWelcomeAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcomeAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWelcomeGuestName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWelcomeGuestName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''welcomeNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents welcomeNote As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblFirstDiscountInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFirstDiscountInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSecondDiscountInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSecondDiscountInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''pid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divstart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divstart As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdoplan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoplan As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''divend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divend As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadioButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton1 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''RadioButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButton2 As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PlanConfirm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlanConfirm As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblAmountTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAmountTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBillToPost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBillToPost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''HtmlBtnPurchase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HtmlBtnPurchase As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ContinueDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ContinueDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''HtmlBtnContinue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HtmlBtnContinue As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As ITCUI.SHMaster
        Get
            Return CType(MyBase.Master, ITCUI.SHMaster)
        End Get
    End Property
End Class
